# Generated by Django 5.1.1 on 2024-11-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_ID', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_ID', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('description', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtimes', models.CharField(max_length=50, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.branch')),
                ('cinema_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
                ('movie_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cinema_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema_movie')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.customer')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seats')),
            ],
        ),
    ]
