# Generated by Django 5.1.3 on 2024-11-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='defaultusername', max_length=150),
        ),
    ]
