# Generated by Django 5.1.1 on 2024-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_customer_password_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema_movie',
            name='branch',
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
