# Generated by Django 5.1.2 on 2024-10-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_cinema_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_movie',
            name='showtimes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
