# Generated by Django 5.1.2 on 2024-10-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_cinema_movie_showtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_movie',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.branch'),
        ),
    ]
