# Generated by Django 5.1.2 on 2024-10-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_cinema_movie_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cinema_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema_movie')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.customer')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seats')),
            ],
        ),
    ]
